### ISSUE TITLE
Could you please add a license to the repo?

### ISSUE THREAD

**Issue by olcai** [ollema/xtea#1]
Hej!

I'd like to use this library in a proprietary project. I can currently not do that since this repo is without any license as far as I can tell.

I would humbly request that you add some kind of license to this repo so that its legal status is clear. For our purposes a permissive free software license such as MIT or BSD would be perfect, but this is of course your decision.

Thank you for your time!
/Erik

**Comment by rymdolle** [comment]
Hi!
I've now added the Apache Licence.
Thanks for mentioning!
