### ISSUE TITLE
*.so and *.o files in package does not work on macOS

### ISSUE THREAD

**Issue by barthez** [ollema/xtea#2]
Hello @rymdolle,

Thank you very much for creating this package it is really useful.

I have noticed that package includes `*.so` and `*.o` files that are compiled on your machine:
```bash
$ find deps/xtea/ -name '*.so' -o -name '*.o'
deps/xtea//c_src/xtea_nif.o
deps/xtea//priv/xtea.so
```

They do not work on macOS. To make the package work locally for me I removed those files and did recompile the package `mix deps.compile`.

Would you mind releasing new version of the package that does not include those files?

Thanks a mill,
Bartek

**Comment by rymdolle** [comment]
Hi,
This is now fixed

Thanks!

**Comment by barthez** [comment]
You are awesome 💙💚💛💜
